export const MAPS_ENDPOINT = 'https://maps.googleapis.com/maps/api/geocode/json'
export const API_ENDPOINT = "https://gymhawk-2ed7f.web.app/api"
export const OTHER_API_ENDPOINT = "https://us-central1-gymhawk-2ed7f.cloudfunctions.net"
export const EMAIL = 'eceseniordesign20242025@gmail.com';
export const ZOOM_LEVEL = 19
export const STATUS_OFFLINE = "OFFLINE";
export const STATUS_UNKNOWN = "UNKNOWN";
export const STATUS_ONLINE = "ONLINE";
export const ONE_SECOND = 1000;
export const ONE_MINUTE = 60 * ONE_SECOND;
export const ONE_HOUR = 60 * ONE_MINUTE;
export const CACHE_DURATION = ONE_HOUR;