name: Deploy Functions to Firebase
on:
  push:
    branches:
      - main
jobs:
  main:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.IDENTITY_POOL_PROVIDER }}
        service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EMAIL }}
        project_id: gymhawk-2ed7f

    - name: Deploy Firebase Functions
    run: |
        npm install -g firebase-tools
        firebase deploy --only functions --project=gymhawk-2ed7f
    env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}